#!/bin/bash
set -e # exit with nonzero exit code if anything fails
if [ "$TRAVIS" = "true" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
  mkdir _site
  cd _site
  cp ../mega-structure.html .
  cp ../bundle.js ../synthesizer-webworker.js ../OrbitControls.js ../codemirror-eisen-script-mode.js .
  cp -r ../bower_components .
  git init
  git config --global user.email "sb@unhexhexium.net"
  git config --global user.name "ssrb (via Travis CI)"
  git config --global push.default simple
  
  git add .
  git commit -m "Deploy to GitHub Pages"
  
  # Force push from the current repo's master branch to the remote
  # repo's gh-pages branch. (All previous history on the gh-pages branch
  # will be lost, since we are overwriting it.) We redirect any output to
  # /dev/null to hide any sensitive credential data that might otherwise be exposed.
  git push --force --quiet git@github.com:ssrb/mega-structure.git master:gh-pages > /dev/null 2>&1
else
  echo 'You are not running Travis-CI on the master branch !'
fi
